#ifndef HSALIB_HPP_
#define HSALIB_HPP_

#include "hsa.h"
#include "hsa_ext_finalize.h"
#include "hsa_ext_private_amd.h"
#include "thread/thread.hpp"
#include "utils/debug.hpp"
using namespace amd;
namespace oclhsa {

#define HSA_PLACE HSA_CALL

typedef decltype(hsa_init)* pfn_hsa_init;
typedef decltype(hsa_shut_down)* pfn_hsa_shut_down;
typedef decltype(hsa_system_get_info)* pfn_hsa_system_get_info;
typedef decltype(hsa_iterate_agents)* pfn_hsa_iterate_agents;
typedef decltype(hsa_agent_get_info)* pfn_hsa_agent_get_info;
typedef decltype(hsa_queue_create)* pfn_hsa_queue_create;
typedef decltype(hsa_queue_destroy)* pfn_hsa_queue_destroy;
typedef decltype(hsa_queue_inactivate)* pfn_hsa_queue_inactivate;
typedef decltype(hsa_queue_load_read_index_acquire)* pfn_hsa_queue_load_read_index_acquire;
typedef decltype(hsa_queue_load_read_index_relaxed)* pfn_hsa_queue_load_read_index_relaxed;
typedef decltype(hsa_queue_load_write_index_acquire)* pfn_hsa_queue_load_write_index_acquire;
typedef decltype(hsa_queue_load_write_index_relaxed)* pfn_hsa_queue_load_write_index_relaxed;
typedef decltype(hsa_queue_store_write_index_relaxed)* pfn_hsa_queue_store_write_index_relaxed;
typedef decltype(hsa_queue_store_write_index_release)* pfn_hsa_queue_store_write_index_release;
typedef decltype(hsa_queue_cas_write_index_acq_rel)* pfn_hsa_queue_cas_write_index_acq_rel;
typedef decltype(hsa_queue_cas_write_index_acquire)* pfn_hsa_queue_cas_write_index_acquire;
typedef decltype(hsa_queue_cas_write_index_relaxed)* pfn_hsa_queue_cas_write_index_relaxed;
typedef decltype(hsa_queue_cas_write_index_release)* pfn_hsa_queue_cas_write_index_release;
typedef decltype(hsa_queue_add_write_index_acq_rel)* pfn_hsa_queue_add_write_index_acq_rel;
typedef decltype(hsa_queue_add_write_index_acquire)* pfn_hsa_queue_add_write_index_acquire;
typedef decltype(hsa_queue_add_write_index_relaxed)* pfn_hsa_queue_add_write_index_relaxed;
typedef decltype(hsa_queue_add_write_index_release)* pfn_hsa_queue_add_write_index_release;
typedef decltype(hsa_queue_store_read_index_relaxed)* pfn_hsa_queue_store_read_index_relaxed;
typedef decltype(hsa_queue_store_read_index_release)* pfn_hsa_queue_store_read_index_release;
typedef decltype(hsa_agent_iterate_regions)* pfn_hsa_agent_iterate_regions;
typedef decltype(hsa_region_get_info)* pfn_hsa_region_get_info;
typedef decltype(hsa_memory_register)* pfn_hsa_memory_register;
typedef decltype(hsa_memory_deregister)* pfn_hsa_memory_deregister;
typedef decltype(hsa_memory_allocate)* pfn_hsa_memory_allocate;
typedef decltype(hsa_memory_free)* pfn_hsa_memory_free;
typedef decltype(hsa_signal_create)* pfn_hsa_signal_create;
typedef decltype(hsa_signal_destroy)* pfn_hsa_signal_destroy;
typedef decltype(hsa_signal_load_relaxed)* pfn_hsa_signal_load_relaxed;
typedef decltype(hsa_signal_load_acquire)* pfn_hsa_signal_load_acquire;
typedef decltype(hsa_signal_store_relaxed)* pfn_hsa_signal_store_relaxed;
typedef decltype(hsa_signal_store_release)* pfn_hsa_signal_store_release;
typedef decltype(hsa_signal_wait_relaxed)* pfn_hsa_signal_wait_relaxed;
typedef decltype(hsa_signal_wait_acquire)* pfn_hsa_signal_wait_acquire;
typedef decltype(hsa_signal_and_relaxed)* pfn_hsa_signal_and_relaxed;
typedef decltype(hsa_signal_and_acquire)* pfn_hsa_signal_and_acquire;
typedef decltype(hsa_signal_and_release)* pfn_hsa_signal_and_release;
typedef decltype(hsa_signal_and_acq_rel)* pfn_hsa_signal_and_acq_rel;
typedef decltype(hsa_signal_or_relaxed)* pfn_hsa_signal_or_relaxed;
typedef decltype(hsa_signal_or_acquire)* pfn_hsa_signal_or_acquire;
typedef decltype(hsa_signal_or_release)* pfn_hsa_signal_or_release;
typedef decltype(hsa_signal_or_acq_rel)* pfn_hsa_signal_or_acq_rel;
typedef decltype(hsa_signal_xor_relaxed)* pfn_hsa_signal_xor_relaxed;
typedef decltype(hsa_signal_xor_acquire)* pfn_hsa_signal_xor_acquire;
typedef decltype(hsa_signal_xor_release)* pfn_hsa_signal_xor_release;
typedef decltype(hsa_signal_xor_acq_rel)* pfn_hsa_signal_xor_acq_rel;
typedef decltype(hsa_signal_exchange_relaxed)* pfn_hsa_signal_exchange_relaxed;
typedef decltype(hsa_signal_exchange_acquire)* pfn_hsa_signal_exchange_acquire;
typedef decltype(hsa_signal_exchange_release)* pfn_hsa_signal_exchange_release;
typedef decltype(hsa_signal_exchange_acq_rel)* pfn_hsa_signal_exchange_acq_rel;
typedef decltype(hsa_signal_add_relaxed)* pfn_hsa_signal_add_relaxed;
typedef decltype(hsa_signal_add_acquire)* pfn_hsa_signal_add_acquire;
typedef decltype(hsa_signal_add_release)* pfn_hsa_signal_add_release;
typedef decltype(hsa_signal_add_acq_rel)* pfn_hsa_signal_add_acq_rel;
typedef decltype(hsa_signal_subtract_relaxed)* pfn_hsa_signal_subtract_relaxed;
typedef decltype(hsa_signal_subtract_acquire)* pfn_hsa_signal_subtract_acquire;
typedef decltype(hsa_signal_subtract_release)* pfn_hsa_signal_subtract_release;
typedef decltype(hsa_signal_subtract_acq_rel)* pfn_hsa_signal_subtract_acq_rel;
typedef decltype(hsa_signal_cas_relaxed)* pfn_hsa_signal_cas_relaxed;
typedef decltype(hsa_signal_cas_acquire)* pfn_hsa_signal_cas_acquire;
typedef decltype(hsa_signal_cas_release)* pfn_hsa_signal_cas_release;
typedef decltype(hsa_signal_cas_acq_rel)* pfn_hsa_signal_cas_acq_rel;
typedef decltype(hsa_status_string)* pfn_hsa_status_string;
typedef decltype(hsa_ext_program_create)* pfn_hsa_ext_program_create;
typedef decltype(hsa_ext_program_destroy)* pfn_hsa_ext_program_destroy;
typedef decltype(hsa_ext_add_module)* pfn_hsa_ext_add_module;
typedef decltype(hsa_ext_finalize_program)* pfn_hsa_ext_finalize_program;
typedef decltype(hsa_ext_query_program_agent_id)* pfn_hsa_ext_query_program_agent_id;
typedef decltype(hsa_ext_query_program_agent_count)* pfn_hsa_ext_query_program_agent_count;
typedef decltype(hsa_ext_query_program_agents)* pfn_hsa_ext_query_program_agents;
typedef decltype(hsa_ext_query_program_module_count)* pfn_hsa_ext_query_program_module_count;
typedef decltype(hsa_ext_query_program_modules)* pfn_hsa_ext_query_program_modules;
typedef decltype(hsa_ext_query_program_brig_module)* pfn_hsa_ext_query_program_brig_module;
typedef decltype(hsa_ext_query_call_convention)* pfn_hsa_ext_query_call_convention;
typedef decltype(hsa_ext_query_symbol_definition)* pfn_hsa_ext_query_symbol_definition;
typedef decltype(hsa_ext_define_program_allocation_global_variable_address)* pfn_hsa_ext_define_program_allocation_global_variable_address;
typedef decltype(hsa_ext_query_program_allocation_global_variable_address)* pfn_hsa_ext_query_program_allocation_global_variable_address;
typedef decltype(hsa_ext_define_agent_allocation_global_variable_address)* pfn_hsa_ext_define_agent_allocation_global_variable_address;
typedef decltype(hsa_ext_query_agent_global_variable_address)* pfn_hsa_ext_query_agent_global_variable_address;
typedef decltype(hsa_ext_define_readonly_variable_address)* pfn_hsa_ext_define_readonly_variable_address;
typedef decltype(hsa_ext_query_readonly_variable_address)* pfn_hsa_ext_query_readonly_variable_address;
typedef decltype(hsa_ext_query_kernel_descriptor_address)* pfn_hsa_ext_query_kernel_descriptor_address;
typedef decltype(hsa_ext_query_indirect_function_descriptor_address)* pfn_hsa_ext_query_indirect_function_descriptor_address;
typedef decltype(hsa_ext_validate_program)* pfn_hsa_ext_validate_program;
typedef decltype(hsa_ext_validate_program_module)* pfn_hsa_ext_validate_program_module;
typedef decltype(hsa_ext_serialize_program)* pfn_hsa_ext_serialize_program;
typedef decltype(hsa_ext_deserialize_program)* pfn_hsa_ext_deserialize_program;
typedef decltype(hsa_ext_get_memory_type)* pfn_hsa_ext_get_memory_type;
typedef decltype(hsa_ext_set_memory_type)* pfn_hsa_ext_set_memory_type;

struct HsaLibApi
{
	pfn_hsa_init _hsa_init;
	pfn_hsa_shut_down _hsa_shut_down;
	pfn_hsa_system_get_info _hsa_system_get_info;
	pfn_hsa_iterate_agents _hsa_iterate_agents;
	pfn_hsa_agent_get_info _hsa_agent_get_info;
	pfn_hsa_queue_create _hsa_queue_create;
	pfn_hsa_queue_destroy _hsa_queue_destroy;
	pfn_hsa_queue_inactivate _hsa_queue_inactivate;
	pfn_hsa_queue_load_read_index_acquire _hsa_queue_load_read_index_acquire;
	pfn_hsa_queue_load_read_index_relaxed _hsa_queue_load_read_index_relaxed;
	pfn_hsa_queue_load_write_index_acquire _hsa_queue_load_write_index_acquire;
	pfn_hsa_queue_load_write_index_relaxed _hsa_queue_load_write_index_relaxed;
	pfn_hsa_queue_store_write_index_relaxed _hsa_queue_store_write_index_relaxed;
	pfn_hsa_queue_store_write_index_release _hsa_queue_store_write_index_release;
	pfn_hsa_queue_cas_write_index_acq_rel _hsa_queue_cas_write_index_acq_rel;
	pfn_hsa_queue_cas_write_index_acquire _hsa_queue_cas_write_index_acquire;
	pfn_hsa_queue_cas_write_index_relaxed _hsa_queue_cas_write_index_relaxed;
	pfn_hsa_queue_cas_write_index_release _hsa_queue_cas_write_index_release;
	pfn_hsa_queue_add_write_index_acq_rel _hsa_queue_add_write_index_acq_rel;
	pfn_hsa_queue_add_write_index_acquire _hsa_queue_add_write_index_acquire;
	pfn_hsa_queue_add_write_index_relaxed _hsa_queue_add_write_index_relaxed;
	pfn_hsa_queue_add_write_index_release _hsa_queue_add_write_index_release;
	pfn_hsa_queue_store_read_index_relaxed _hsa_queue_store_read_index_relaxed;
	pfn_hsa_queue_store_read_index_release _hsa_queue_store_read_index_release;
	pfn_hsa_agent_iterate_regions _hsa_agent_iterate_regions;
	pfn_hsa_region_get_info _hsa_region_get_info;
	pfn_hsa_memory_register _hsa_memory_register;
	pfn_hsa_memory_deregister _hsa_memory_deregister;
	pfn_hsa_memory_allocate _hsa_memory_allocate;
	pfn_hsa_memory_free _hsa_memory_free;
	pfn_hsa_signal_create _hsa_signal_create;
	pfn_hsa_signal_destroy _hsa_signal_destroy;
	pfn_hsa_signal_load_relaxed _hsa_signal_load_relaxed;
	pfn_hsa_signal_load_acquire _hsa_signal_load_acquire;
	pfn_hsa_signal_store_relaxed _hsa_signal_store_relaxed;
	pfn_hsa_signal_store_release _hsa_signal_store_release;
	pfn_hsa_signal_wait_relaxed _hsa_signal_wait_relaxed;
	pfn_hsa_signal_wait_acquire _hsa_signal_wait_acquire;
	pfn_hsa_signal_and_relaxed _hsa_signal_and_relaxed;
	pfn_hsa_signal_and_acquire _hsa_signal_and_acquire;
	pfn_hsa_signal_and_release _hsa_signal_and_release;
	pfn_hsa_signal_and_acq_rel _hsa_signal_and_acq_rel;
	pfn_hsa_signal_or_relaxed _hsa_signal_or_relaxed;
	pfn_hsa_signal_or_acquire _hsa_signal_or_acquire;
	pfn_hsa_signal_or_release _hsa_signal_or_release;
	pfn_hsa_signal_or_acq_rel _hsa_signal_or_acq_rel;
	pfn_hsa_signal_xor_relaxed _hsa_signal_xor_relaxed;
	pfn_hsa_signal_xor_acquire _hsa_signal_xor_acquire;
	pfn_hsa_signal_xor_release _hsa_signal_xor_release;
	pfn_hsa_signal_xor_acq_rel _hsa_signal_xor_acq_rel;
	pfn_hsa_signal_exchange_relaxed _hsa_signal_exchange_relaxed;
	pfn_hsa_signal_exchange_acquire _hsa_signal_exchange_acquire;
	pfn_hsa_signal_exchange_release _hsa_signal_exchange_release;
	pfn_hsa_signal_exchange_acq_rel _hsa_signal_exchange_acq_rel;
	pfn_hsa_signal_add_relaxed _hsa_signal_add_relaxed;
	pfn_hsa_signal_add_acquire _hsa_signal_add_acquire;
	pfn_hsa_signal_add_release _hsa_signal_add_release;
	pfn_hsa_signal_add_acq_rel _hsa_signal_add_acq_rel;
	pfn_hsa_signal_subtract_relaxed _hsa_signal_subtract_relaxed;
	pfn_hsa_signal_subtract_acquire _hsa_signal_subtract_acquire;
	pfn_hsa_signal_subtract_release _hsa_signal_subtract_release;
	pfn_hsa_signal_subtract_acq_rel _hsa_signal_subtract_acq_rel;
	pfn_hsa_signal_cas_relaxed _hsa_signal_cas_relaxed;
	pfn_hsa_signal_cas_acquire _hsa_signal_cas_acquire;
	pfn_hsa_signal_cas_release _hsa_signal_cas_release;
	pfn_hsa_signal_cas_acq_rel _hsa_signal_cas_acq_rel;
	pfn_hsa_status_string _hsa_status_string;
	pfn_hsa_ext_program_create _hsa_ext_program_create;
	pfn_hsa_ext_program_destroy _hsa_ext_program_destroy;
	pfn_hsa_ext_add_module _hsa_ext_add_module;
	pfn_hsa_ext_finalize_program _hsa_ext_finalize_program;
	pfn_hsa_ext_query_program_agent_id _hsa_ext_query_program_agent_id;
	pfn_hsa_ext_query_program_agent_count _hsa_ext_query_program_agent_count;
	pfn_hsa_ext_query_program_agents _hsa_ext_query_program_agents;
	pfn_hsa_ext_query_program_module_count _hsa_ext_query_program_module_count;
	pfn_hsa_ext_query_program_modules _hsa_ext_query_program_modules;
	pfn_hsa_ext_query_program_brig_module _hsa_ext_query_program_brig_module;
	pfn_hsa_ext_query_call_convention _hsa_ext_query_call_convention;
	pfn_hsa_ext_query_symbol_definition _hsa_ext_query_symbol_definition;
	pfn_hsa_ext_define_program_allocation_global_variable_address _hsa_ext_define_program_allocation_global_variable_address;
	pfn_hsa_ext_query_program_allocation_global_variable_address _hsa_ext_query_program_allocation_global_variable_address;
	pfn_hsa_ext_define_agent_allocation_global_variable_address _hsa_ext_define_agent_allocation_global_variable_address;
	pfn_hsa_ext_query_agent_global_variable_address _hsa_ext_query_agent_global_variable_address;
	pfn_hsa_ext_define_readonly_variable_address _hsa_ext_define_readonly_variable_address;
	pfn_hsa_ext_query_readonly_variable_address _hsa_ext_query_readonly_variable_address;
	pfn_hsa_ext_query_kernel_descriptor_address _hsa_ext_query_kernel_descriptor_address;
	pfn_hsa_ext_query_indirect_function_descriptor_address _hsa_ext_query_indirect_function_descriptor_address;
	pfn_hsa_ext_validate_program _hsa_ext_validate_program;
	pfn_hsa_ext_validate_program_module _hsa_ext_validate_program_module;
	pfn_hsa_ext_serialize_program _hsa_ext_serialize_program;
	pfn_hsa_ext_deserialize_program _hsa_ext_deserialize_program;
	pfn_hsa_ext_get_memory_type _hsa_ext_get_memory_type;
	pfn_hsa_ext_set_memory_type _hsa_ext_set_memory_type;
};
//
// Use g_  prefix for all global variables.
//
extern void* g_hsaModule;
extern HsaLibApi g_hsaLibApi;

// Note: initializes global variable g_complibApi.
// Not sure what error values we have, for now returning false on failure.
bool LoadHsaLib();
void UnloadHsaLib();
}
#endif
